SellerPlan.create(
    name: "Basic",
    stripe_id: "Basic-Monthly",
    amount: 19900,
    interval: "month",
    num_of_products: 50,
    num_of_locations: 5,
    num_of_sub_accounts: 5,
    analytics: "Basic",
    pause: false
)

SellerPlan.create(
    name: "Advanced",
    stripe_id: "Advanced-Monthly",
    amount: 29900,
    interval: "month",
    num_of_products: 200,
    num_of_locations: 15,
    num_of_sub_accounts: 15,
    analytics: "Advanced",
    pause: false
)

food = Category.create(name: "Food & Beverages", pause: false)
    beverages = Category.create(name: "Beverages", parent: food, pause: false)
        alcoholic_beverages = Category.create(name: "Alcoholic Beverages", parent: food, pause: false)
            beer = Category.create(name: "Beer", parent: alcoholic_beverages, pause: false)
            bitters = Category.create(name: "Bitters", parent: alcoholic_beverages, pause: false)
            cocktail_mixes = Category.create(name: "Cocktail Mixes", parent: alcoholic_beverages, pause: false)
                frozen_cocktail_mixes = Category.create(name: "Frozen Cocktail Mixes", parent: cocktail_mixes, pause: false)
                shelf_stable_cocktail_mixes = Category.create(name: "Shelf-stable Cocktail Mixes", parent: cocktail_mixes, pause: false)
            flavored_alcoholic_beverages = Category.create(name: "Flavored Alcoholic Beverages", parent: alcoholic_beverages, pause: false)
            hard_cider = Category.create(name: "Hard Cider", parent: alcoholic_beverages, pause: false)
            liquor_and_spirits = Category.create(name: "Liquor & Spirits", parent: alcoholic_beverages, pause: false)
                absinthe = Category.create(name: "Absinthe", parent: liquor_and_spirits, pause: false)
                brandy = Category.create(name: "Brandy", parent: liquor_and_spirits, pause: false)
                gin = Category.create(name: "Gin", parent: liquor_and_spirits, pause: false)
                liqueurs = Category.create(name: "Liqueurs", parent: liquor_and_spirits, pause: false)
                rum = Category.create(name: "Rum", parent: liquor_and_spirits, pause: false)
                shochu_and_soju = Category.create(name: "Shochu & Soju", parent: liquor_and_spirits, pause: false)
                    shochu = Category.create(name: "Shochu", parent: shochu_and_soju, pause: false)
                    soju = Category.create(name: "Soju", parent: shochu_and_soju, pause: false)
                tequila = Category.create(name: "Tequila", parent: liquor_and_spirits, pause: false)
                vodka = Category.create(name: "Vodka", parent: liquor_and_spirits, pause: false)
                whiskey = Category.create(name: "Whiskey", parent: liquor_and_spirits, pause: false)
            wine = Category.create(name: "Wine", parent: alcoholic_beverages, pause: false)
        buttermilk = Category.create(name: "Buttermilk", parent: food, pause: false)
        coffee = Category.create(name: "Coffee", parent: food, pause: false)
        eggnog = Category.create(name: "Eggnog", parent: food, pause: false)
        fruit_flavored_drinks = Category.create(name: "Fruit Flavored Drinks", parent: food, pause: false) 
        hot_chocolate = Category.create(name: "Hot Chocolate", parent: food, pause: false)
        juice = Category.create(name: "Juice", parent: food, pause: false)
        milk = Category.create(name: "Milk", parent: food, pause: false)
        non_dairy_milk = Category.create(name: "Non-Dairy Milk", parent: food, pause: false)
        powdered_beverage_mixes = Category.create(name: "Powdered Beverage Mixes", parent: food, pause: false)
        soda = Category.create(name: "Soda", parent: food, pause: false)
        sports_and_energy_drinks = Category.create(name: "Sports & Energy Drinks", parent: food, pause: false)
        tea_and_infusions = Category.create(name: "Tea & Infusions", parent: food, pause: false)
        vinegar_drinks = Category.create(name: "Vinegar Drinks", parent: food, pause: false)
        water = Category.create(name: "Water", parent: food, pause: false)
            carbonated_water = Category.create(name: "Carbonated Water", parent: water, pause: false)
                flavored_carbonated_water = Category.create(name: "Flavored Carbonated Water", parent: carbonated_water, pause: false)
                unflavored_carbonated_water = Category.create(name: "Unflavored Carbonated Water", parent: carbonated_water, pause: false)
            distilled_water = Category.create(name: "Distilled Water", parent: water, pause: false)
            flat_mineral_water = Category.create(name: "Flat Mineral Water", parent: water, pause: false)
            spring_water = Category.create(name: "Spring Water", parent: water, pause: false)
    food_products = Category.create(name: "Food Products", parent: food, pause: false)
        bakery = Category.create(name: "Bakery", parent: food_products, pause: false)
            bagels = Category.create(name: "Bagels", parent: bakery, pause: false)
            bakery_assortments = Category.create(name: "Bakery Assortments", parent: bakery, pause: false)
            breads_and_buns = Category.create(name: "Breads & Buns", parent: bakery, pause: false)
            cakes_and_dessert_bars = Category.create(name: "Cakes & Dessert Bars", parent: bakery, pause: false)
            coffee_cakes = Category.create(name: "Coffee Cakes", parent: bakery, pause: false)
            cookies = Category.create(name: "Cookies", parent: bakery, pause: false)
            cupcakes = Category.create(name: "Cupcakes", parent: bakery, pause: false)
            donuts = Category.create(name: "Donuts", parent: bakery, pause: false)
            ice_cream_cones = Category.create(name: "Ice Cream Cones", parent: bakery, pause: false)
            muffins = Category.create(name: "Muffins", parent: bakery, pause: false)
            pasties_and_scones = Category.create(name: "Pastries & Scones", parent: bakery, pause: false)
            pies_and_tarts = Category.create(name: "Pies & Tarts", parent: bakery, pause: false)
            taco_shells_and_tostadas = Category.create(name: "Taco Shells & Tostadas", parent: bakery, pause: false)
            torillas_and_wraps = Category.create(name: "Tortillas & Wraps", parent: bakery, pause: false)
        candied_and_chocolate_covered_fruit = Category.create(name: "Candied & Chocolate Covered Fruit", parent: food_products, pause: false)
        candy_and_chocolate = Category.create(name: "Candy & Chocolate", parent: food_products, pause: false)
        condiments_and_sauces = Category.create(name: "Condiments & Sauces", parent: food_products, pause: false)
            coctail_sauce = Category.create(name: "Cocktail Sauce", parent: condiments_and_sauces, pause: false)
            curry_sauce = Category.create(name: "Curry Sauce", parent: condiments_and_sauces, pause: false)
            dessert_toppings = Category.create(name: "Dessert Toppings", parent: condiments_and_sauces, pause: false)
                fruit_toppings = Category.create(name: "Fruit Toppings", parent: dessert_toppings, pause: false)
                ice_cream_syrup = Category.create(name: "Ice Cream Syrup", parent: dessert_toppings, pause: false)
            fish_sauce = Category.create(name: "Fish Sauce", parent: condiments_and_sauces, pause: false)
            gravy = Category.create(name: "Gravy", parent: condiments_and_sauces, pause: false)
            honey = Category.create(name: "Honey", parent: condiments_and_sauces, pause: false)
            horseradish_sauce = Category.create(name: "Horseradish Sauce", parent: condiments_and_sauces, pause: false)
            hot_sauce = Category.create(name: "Hot Sauce", parent: condiments_and_sauces, pause: false)
            ketchup = Category.create(name: "Ketchup", parent: condiments_and_sauces, pause: false)
            marinades_and_grilling_sauces = Category.create(name: "Marinades & Grilling Sauces", parent: condiments_and_sauces, pause: false)
            mayonnaise = Category.create(name: "Mayonnaise", parent: condiments_and_sauces, pause: false)
            mustard = Category.create(name: "Mustard", parent: condiments_and_sauces, pause: false)
            olives_and_capers = Category.create(name: "Olives & Capers", parent: condiments_and_sauces, pause: false)
            pasta_sauce = Category.create(name: "Pasta Sauce", parent: condiments_and_sauces, pause: false)
            pickled_fruits_and_vegetables = Category.create(name: "Pickled Fruits & Vegetables", parent: condiments_and_sauces, pause: false)
            pizza_sauce = Category.create(name: "Pizza Sauce", parent: condiments_and_sauces, pause: false)
            relish_and_chutney = Category.create(name: "Relish & Chutney", parent: condiments_and_sauces, pause: false)
            salad_dressing = Category.create(name: "Salad Dressing", parent: condiments_and_sauces, pause: false)
            satay_sauce = Category.create(name: "Satay Sauce", parent: condiments_and_sauces, pause: false)
            soy_sauce = Category.create(name: "Soy Sauce", parent: condiments_and_sauces, pause: false)
            sweet_and_sour_sauces = Category.create(name: "Sweet & Sour Sauces", parent: condiments_and_sauces, pause: false)
            syrup = Category.create(name: "Syrup", parent: condiments_and_sauces, pause: false)
            tahini = Category.create(name: "Tahini", parent: condiments_and_sauces, pause: false)
            tartar_sauce = Category.create(name: "Tartar Sauce", parent: condiments_and_sauces, pause: false)
            white_and_cream_sauces = Category.create(name: "White & Cream Sauces", parent: condiments_and_sauces, pause: false)
            worcestershite_sauce = Category.create(name: "Worcestershire Sauce", parent: condiments_and_sauces, pause: false)
        cooking_and_baking_ingredients = Category.create(name: "Cooking & Baking Ingredients", parent: food_products, pause: false)
            baking_chips = Category.create(name: "Baking Chips", parent: cooking_and_baking_ingredients, pause: false)
            baking_chocolate = Category.create(name: "Baking Chocolate", parent: cooking_and_baking_ingredients, pause: false)
            baking_flavors_and_extracts = Category.create(name: "Baking Flavors & Extracts", parent: cooking_and_baking_ingredients, pause: false)
            baking_mixes = Category.create(name: "Baking Mixes", parent: cooking_and_baking_ingredients, pause: false)
            baking_powder = Category.create(name: "Baking Powder", parent: cooking_and_baking_ingredients, pause: false)
            baking_soda = Category.create(name: "Baking Soda", parent: cooking_and_baking_ingredients, pause: false)
            batter_and_coating_mixes = Category.create(name: "Batter & Coating Mixes", parent: cooking_and_baking_ingredients, pause: false)
            bean_paste = Category.create(name: "Bean Paste", parent: cooking_and_baking_ingredients, pause: false)
            bread_crumbs = Category.create(name: "Bread Crumbs", parent: cooking_and_baking_ingredients, pause: false)
            canned_and_dry_milk = Category.create(name: "Canned & Dry Milk", parent: cooking_and_baking_ingredients, pause: false)
            cookie_decorating_kits = Category.create(name: "Cookie Decorating Kits", parent: cooking_and_baking_ingredients, pause: false)
            cooking_oils = Category.create(name: "Cooking Oils", parent: cooking_and_baking_ingredients, pause: false)
            cooking_starch = Category.create(name: "Cooking Starch", parent: cooking_and_baking_ingredients, pause: false)
            cooking_wine = Category.create(name: "Cooking Wine", parent: cooking_and_baking_ingredients, pause: false)
            corn_syrup = Category.create(name: "Corn Syrup", parent: cooking_and_baking_ingredients, pause: false)
            dough = Category.create(name: "Dough", parent: cooking_and_baking_ingredients, pause: false)
                bread_and_pastry_dough = Category.create(name: "Bread & Pastry Dough", parent: dough, pause: false)
                cookie_and_brownie_dough = Category.create(name: "Cookie & Brownie Dough", parent: dough, pause: false)
                pie_crusts = Category.create(name: "Pie Crusts", parent: dough, pause: false)
            edible_baking_decorations = Category.create(name: "Edible Baking Decorations", parent: cooking_and_baking_ingredients, pause: false)
            egg_replacers = Category.create(name: "Egg Replacers", parent: cooking_and_baking_ingredients, pause: false)
            floss_sugar = Category.create(name: "Floss Sugar", parent: cooking_and_baking_ingredients, pause: false)
            flour = Category.create(name: "Flour", parent: cooking_and_baking_ingredients, pause: false)
            food_coloring = Category.create(name: "Food Coloring", parent: cooking_and_baking_ingredients, pause: false)
            frosting_and_icing = Category.create(name: "Frosting & Icing", parent: cooking_and_baking_ingredients, pause: false)
            lemon_and_lime_juice = Category.create(name: "Lemon & Lime Juice", parent: cooking_and_baking_ingredients, pause: false)
            marshmallows = Category.create(name: "Marshmallows", parent: cooking_and_baking_ingredients, pause: false)
            meal = Category.create(name: "Meal", parent: cooking_and_baking_ingredients, pause: false)
            molasses = Category.create(name: "Molasses", parent: cooking_and_baking_ingredients, pause: false)
            pie_and_pastry_fillings = Category.create(name: "Pie & Pastry Fillings", parent: cooking_and_baking_ingredients, pause: false)
            shortening_and_lard = Category.create(name: "Shortening & Lard", parent: cooking_and_baking_ingredients, pause: false)
            starter_and_cultures = Category.create(name: "Starter Cultures", parent: cooking_and_baking_ingredients, pause: false)
            sugar_and_sweeteners = Category.create(name: "Sugar & Sweeteners", parent: cooking_and_baking_ingredients, pause: false)
            tapioca_pearls = Category.create(name: "Tapioca Pearls", parent: cooking_and_baking_ingredients, pause: false)
            tomato_paste = Category.create(name: "Tomato Paste", parent: cooking_and_baking_ingredients, pause: false)
            unflavored_gelatin = Category.create(name: "Unflavored Gelatin", parent: cooking_and_baking_ingredients, pause: false)
            vinegar = Category.create(name: "Vinegar", parent: cooking_and_baking_ingredients, pause: false)
            waffle_and_pancake_mixes = Category.create(name: "Waffle & Pancake Mixes", parent: cooking_and_baking_ingredients, pause: false)
            yeast = Category.create(name: "Yeast", parent: cooking_and_baking_ingredients, pause: false)
        dairy_products = Category.create(name: "Dairy Products", parent: food_products, pause: false)
            butter_and_margarine = Category.create(name: "Butter & Margarine", parent: dairy_products, pause: false)
            cheese = Category.create(name: "Cheese", parent: dairy_products, pause: false)
            coffee_creamer = Category.create(name: "Coffee Creamer", parent: dairy_products, pause: false)
            cottage_cheese = Category.create(name: "Cottage Cheese", parent: dairy_products, pause: false)
            cream = Category.create(name: "Cream", parent: dairy_products, pause: false)
            sour_cream = Category.create(name: "Sour Cream", parent: dairy_products, pause: false)
            whipped_cream = Category.create(name: "Whipped Cream", parent: dairy_products, pause: false)
            yogurt = Category.create(name: "Yogurt", parent: dairy_products, pause: false)
        dips_and_spreads = Category.create(name: "Dips & Spreads", parent: food_products, pause: false)
            apple_butter = Category.create(name: "Apple Butter", parent: dips_and_spreads, pause: false)
            cheese_dips_and_spreads = Category.create(name: "Cheese Dips & Spreads", parent: dips_and_spreads, pause: false)
            cream_cheese = Category.create(name: "Cream Cheese", parent: dips_and_spreads, pause: false)
            guacamole = Category.create(name: "Guacamole", parent: dips_and_spreads, pause: false)
            hummus = Category.create(name: "Hummus", parent: dips_and_spreads, pause: false)
            jams_and_jellies = Category.create(name: "Jams & Jellies", parent: dips_and_spreads, pause: false)
            nut_butters = Category.create(name: "Nut Butters", parent: dips_and_spreads, pause: false)
            salsa = Category.create(name: "Salsa", parent: dips_and_spreads, pause: false)
            tapenade = Category.create(name: "Tapenade", parent: dips_and_spreads, pause: false)
            vegetable_dip = Category.create(name: "Vegetable Dip", parent: dips_and_spreads, pause: false)
        food_gift_baskets = Category.create(name: "Food Gift Baskets", parent: food_products, pause: false)
        frozen_desserts_and_novelties = Category.create(name: "Frozen Desserts & Novelties", parent: food_products, pause: false)
            frozen_desserts_and_novelties = Category.create(name: "Ice Cream & Frozen Yogurt", parent: frozen_desserts_and_novelties, pause: false)
            frozen_desserts_and_novelties = Category.create(name: "Ice Cream Novelties", parent: frozen_desserts_and_novelties, pause: false)
            frozen_desserts_and_novelties = Category.create(name: "Ice Pops", parent: frozen_desserts_and_novelties, pause: false)
        fruits_and_vegetables = Category.create(name: "Fruits & Vegetables", parent: food_products, pause: false)
            canned_and_jarred_fruits = Category.create(name: "Canned & Jarred Fruits", parent: fruits_and_vegetables, pause: false)
            canned_and_jarred_vegetables = Category.create(name: "Canned & Jarred Vegetables", parent: fruits_and_vegetables, pause: false)
            canned_and_prepared_beans = Category.create(name: "Canned & Prepared Beans", parent: fruits_and_vegetables, pause: false)
            dried_fruits = Category.create(name: "Dried Fruits", parent: fruits_and_vegetables, pause: false)
            dried_vegetables = Category.create(name: "Dried Vegetables", parent: fruits_and_vegetables, pause: false)
            dry_beans = Category.create(name: "Dry Beans", parent: fruits_and_vegetables, pause: false)
            fresh_and_frozen_fruits = Category.create(name: "Fresh & Frozen Fruits", parent: fruits_and_vegetables, pause: false)  
                apples = Category.create(name: "Apples", parent: fresh_and_frozen_fruits, pause: false)
                atemoyas = Category.create(name: "Atemoyas", parent: fresh_and_frozen_fruits, pause: false)
                avocados = Category.create(name: "Avocados", parent: fresh_and_frozen_fruits, pause: false)
                babacos = Category.create(name: "Babacos", parent: fresh_and_frozen_fruits, pause: false)
                bananas = Category.create(name: "Bananas", parent: fresh_and_frozen_fruits, pause: false)
                berries = Category.create(name: "Berries", parent: fresh_and_frozen_fruits, pause: false)
                breadfruit = Category.create(name: "Breadfruit", parent: fresh_and_frozen_fruits, pause: false)
                cactus_pears = Category.create(name: "Cactus Pears", parent: fresh_and_frozen_fruits, pause: false)
                cherimoyas = Category.create(name: "Cherimoyas", parent: fresh_and_frozen_fruits, pause: false)
                citrus_fruits = Category.create(name: "Citrus Fruits", parent: fresh_and_frozen_fruits, pause: false)
                    grapefruits = Category.create(name: "Grapefruits", parent: citrus_fruits, pause: false)
                    kumquats = Category.create(name: "Kumquats", parent: citrus_fruits, pause: false)
                    lemons = Category.create(name: "Lemons", parent: citrus_fruits, pause: false)
                    limequats = Category.create(name: "Limequats", parent: citrus_fruits, pause: false)
                    limes = Category.create(name: "Limes", parent: citrus_fruits, pause: false)
                    oranges = Category.create(name: "Oranges", parent: citrus_fruits, pause: false)
                    tangelos = Category.create(name: "Tangelos", parent: citrus_fruits, pause: false)
                coconuts = Category.create(name: "Coconuts", parent: fresh_and_frozen_fruits, pause: false)
                dates = Category.create(name: "Dates", parent: fresh_and_frozen_fruits, pause: false)
                feijoas = Category.create(name: "Feijoas", parent: fresh_and_frozen_fruits, pause: false)
                figs = Category.create(name: "Figs", parent: fresh_and_frozen_fruits, pause: false)
                fruit_mixes = Category.create(name: "Fruit Mixes", parent: fresh_and_frozen_fruits, pause: false)
                grapes = Category.create(name: "Grapes", parent: fresh_and_frozen_fruits, pause: false)
                guavas = Category.create(name: "Guavas", parent: fresh_and_frozen_fruits, pause: false)
                homely_fruits = Category.create(name: "Homely Fruits", parent: fresh_and_frozen_fruits, pause: false)
                kiwis = Category.create(name: "Kiwis", parent: fresh_and_frozen_fruits, pause: false)
                longan = Category.create(name: "Longan", parent: fresh_and_frozen_fruits, pause: false)
                loquats = Category.create(name: "Loquats", parent: fresh_and_frozen_fruits, pause: false)
                lychees = Category.create(name: "Lychees", parent: fresh_and_frozen_fruits, pause: false)
                madroÃ±o = Category.create(name: "MadroÃ±o", parent: fresh_and_frozen_fruits, pause: false)
                mamey = Category.create(name: "Mamey", parent: fresh_and_frozen_fruits, pause: false)
                mangosteens = Category.create(name: "Mangosteens", parent: fresh_and_frozen_fruits, pause: false)
                melons = Category.create(name: "Melons", parent: fresh_and_frozen_fruits, pause: false)
                papayas = Category.create(name: "Papayas", parent: fresh_and_frozen_fruits, pause: false)
                passion_fruit = Category.create(name: "Passion Fruit", parent: fresh_and_frozen_fruits, pause: false)
                pears = Category.create(name: "Pears", parent: fresh_and_frozen_fruits, pause: false)
                persimmons = Category.create(name: "Persimmons", parent: fresh_and_frozen_fruits, pause: false)
                physalis = Category.create(name: "Physalis", parent: fresh_and_frozen_fruits, pause: false)
                pineapples = Category.create(name: "Pineapples", parent: fresh_and_frozen_fruits, pause: false)
                pitahayas = Category.create(name: "Pitahayas", parent: fresh_and_frozen_fruits, pause: false)
                pomegranates = Category.create(name: "Pomegranates", parent: fresh_and_frozen_fruits, pause: false)
                quince = Category.create(name: "Quince", parent: fresh_and_frozen_fruits, pause: false)
                rambutans = Category.create(name: "Rambutans", parent: fresh_and_frozen_fruits, pause: false)
                sapodillo = Category.create(name: "Sapodillo", parent: fresh_and_frozen_fruits, pause: false)
                sapote = Category.create(name: "Sapote", parent: fresh_and_frozen_fruits, pause: false)
                soursops = Category.create(name: "Soursops", parent: fresh_and_frozen_fruits, pause: false)
                starfruits = Category.create(name: "Starfruits", parent: fresh_and_frozen_fruits, pause: false)
                stone_fruits = Category.create(name: "Stone Fruits", parent: fresh_and_frozen_fruits, pause: false)
                    apricots = Category.create(name: "Apricots", parent: fresh_and_frozen_fruits, pause: false)
                    cherries = Category.create(name: "Cherries", parent: fresh_and_frozen_fruits, pause: false)
                    mangoes = Category.create(name: "Mangoes", parent: fresh_and_frozen_fruits, pause: false)
                    peaches_and_nectarines = Category.create(name: "Peaches & Nectarines", parent: fresh_and_frozen_fruits, pause: false)
                    plumcots = Category.create(name: "Plumcots", parent: fresh_and_frozen_fruits, pause: false)
                    plums = Category.create(name: "Plums", parent: fresh_and_frozen_fruits, pause: false)
                sugar_apples = Category.create(name: "Sugar Apples", parent: fresh_and_frozen_fruits, pause: false)
                tamarindo = Category.create(name: "Tamarindo", parent: fresh_and_frozen_fruits, pause: false)
                fresh_and_frozen_vegetables = Category.create(name: "Fresh & Frozen Vegetables", parent: fresh_and_frozen_fruits, pause: false)
                    arracachas = Category.create(name: "Arracachas", parent: fresh_and_frozen_vegetables, pause: false)
                    artichokes = Category.create(name: "Artichokes", parent: fresh_and_frozen_vegetables, pause: false)
                    asparagus = Category.create(name: "Asparagus", parent: fresh_and_frozen_vegetables, pause: false)
                    beans = Category.create(name: "Beans", parent: fresh_and_frozen_vegetables, pause: false)
                    beets = Category.create(name: "Beets", parent: fresh_and_frozen_vegetables, pause: false)
                    borage = Category.create(name: "Borage", parent: fresh_and_frozen_vegetables, pause: false)
                    broccoli = Category.create(name: "Broccoli", parent: fresh_and_frozen_vegetables, pause: false)
                    brussel_sprouts = Category.create(name: "Brussel Sprouts", parent: fresh_and_frozen_vegetables, pause: false)
                    cabbage = Category.create(name: "Cabbage", parent: fresh_and_frozen_vegetables, pause: false)
                    cactus_leaves = Category.create(name: "Cactus Leaves", parent: fresh_and_frozen_vegetables, pause: false)
                    cardoon = Category.create(name: "Cardoon", parent: fresh_and_frozen_vegetables, pause: false)
                    carrots = Category.create(name: "Carrots", parent: fresh_and_frozen_vegetables, pause: false)
                    cauliflower = Category.create(name: "Cauliflower", parent: fresh_and_frozen_vegetables, pause: false)
                    celery = Category.create(name: "Celery", parent: fresh_and_frozen_vegetables, pause: false)
                    celery_roots = Category.create(name: "Celery Roots", parent: fresh_and_frozen_vegetables, pause: false)
                    corn = Category.create(name: "Corn", parent: fresh_and_frozen_vegetables, pause: false)
                    cucumbers = Category.create(name: "Cucumbers", parent: fresh_and_frozen_vegetables, pause: false)
                    eggplants = Category.create(name: "Eggplants", parent: fresh_and_frozen_vegetables, pause: false)
                    fennel_bulbs = Category.create(name: "Fennel Bulbs", parent: fresh_and_frozen_vegetables, pause: false)
                    fiddlehead_ferns = Category.create(name: "Fiddlehead Ferns", parent: fresh_and_frozen_vegetables, pause: false)
                    gai_choy = Category.create(name: "Gai Choy", parent: fresh_and_frozen_vegetables, pause: false)
                    gai_lan = Category.create(name: "Gai Lan", parent: fresh_and_frozen_vegetables, pause: false)
                    garlic = Category.create(name: "Garlic", parent: fresh_and_frozen_vegetables, pause: false)
                    ginger_root = Category.create(name: "Ginger Root", parent: fresh_and_frozen_vegetables, pause: false)
                    gobo_root = Category.create(name: "Gobo Root", parent: fresh_and_frozen_vegetables, pause: false)
                    greens = Category.create(name: "Greens", parent: fresh_and_frozen_vegetables, pause: false)
                        arugula = Category.create(name: "Arugula", parent: greens, pause: false)
                        beet_greens = Category.create(name: "Beet Greens", parent: greens, pause: false)
                        bok_choy = Category.create(name: "Bok Choy", parent: greens, pause: false)
                        chard = Category.create(name: "Chard", parent: greens, pause: false)
                        chicory = Category.create(name: "Chicory", parent: greens, pause: false)
                        choy_sum = Category.create(name: "Choy Sum", parent: greens, pause: false)
                        kale = Category.create(name: "Kale", parent: greens, pause: false)
                        lettuce = Category.create(name: "Lettuce", parent: greens, pause: false)
                        on_choy = Category.create(name: "On Choy", parent: greens, pause: false)
                        salad_mixes = Category.create(name: "Salad Mixes", parent: greens, pause: false)
                        spinach = Category.create(name: "Spinach", parent: greens, pause: false)
                        yu_choy = Category.create(name: "Yu Choy", parent: greens, pause: false)
                    horseradish_root = Category.create(name: "Horseradish Root", parent: fresh_and_frozen_vegetables, pause: false)
                    jicama = Category.create(name: "Jicama", parent: fresh_and_frozen_vegetables, pause: false)
                    kohlrabi = Category.create(name: "Kohlrabi", parent: fresh_and_frozen_vegetables, pause: false)
                    leeks = Category.create(name: "Leeks", parent: fresh_and_frozen_vegetables, pause: false)
                    lotus_roots = Category.create(name: "Lotus Roots", parent: fresh_and_frozen_vegetables, pause: false)
                    malangas = Category.create(name: "Malangas", parent: fresh_and_frozen_vegetables, pause: false)
                    mushrooms = Category.create(name: "Mushrooms", parent: fresh_and_frozen_vegetables, pause: false)
                    okra = Category.create(name: "Okra", parent: fresh_and_frozen_vegetables, pause: false)
                    onions = Category.create(name: "Onions", parent: fresh_and_frozen_vegetables, pause: false)
                    parsley_roots = Category.create(name: "Parsley Roots", parent: fresh_and_frozen_vegetables, pause: false)
                    parsnips = Category.create(name: "Parsnips", parent: fresh_and_frozen_vegetables, pause: false)
                    peas = Category.create(name: "Peas", parent: fresh_and_frozen_vegetables, pause: false)
                    peppers = Category.create(name: "Peppers", parent: fresh_and_frozen_vegetables, pause: false)
                    potatoes = Category.create(name: "Potatoes", parent: fresh_and_frozen_vegetables, pause: false)
                    radishes = Category.create(name: "Radishes", parent: fresh_and_frozen_vegetables, pause: false)
                    rhubarb = Category.create(name: "Rhubarb", parent: fresh_and_frozen_vegetables, pause: false)
                    shallots = Category.create(name: "Shallots", parent: fresh_and_frozen_vegetables, pause: false)
                    sprouts = Category.create(name: "Sprouts", parent: fresh_and_frozen_vegetables, pause: false)
                    squashes_and_gourds = Category.create(name: "Squashes & Gourds", parent: fresh_and_frozen_vegetables, pause: false)
                    sugar_cane = Category.create(name: "Sugar Cane", parent: fresh_and_frozen_vegetables, pause: false)
                    sunchokes = Category.create(name: "Sunchokes", parent: fresh_and_frozen_vegetables, pause: false)
                    sweet_potatoes = Category.create(name: "Sweet Potatoes", parent: fresh_and_frozen_vegetables, pause: false)
                    tamarillos = Category.create(name: "Tamarillos", parent: fresh_and_frozen_vegetables, pause: false)
                    taro_root = Category.create(name: "Taro Root", parent: fresh_and_frozen_vegetables, pause: false)
                    tomatoes = Category.create(name: "Tomatoes", parent: fresh_and_frozen_vegetables, pause: false)
                    turnips_and_rutabagas = Category.create(name: "Turnips & Rutabagas", parent: fresh_and_frozen_vegetables, pause: false)
                    vegetable_mixes = Category.create(name: "Vegetable Mixes", parent: fresh_and_frozen_vegetables, pause: false)
                    water_chestnuts = Category.create(name: "Water Chestnuts", parent: fresh_and_frozen_vegetables, pause: false)
                    watercress = Category.create(name: "Watercress", parent: fresh_and_frozen_vegetables, pause: false)
                    wheatgrass = Category.create(name: "Wheatgrass", parent: fresh_and_frozen_vegetables, pause: false)
                    yams = Category.create(name: "Yams", parent: fresh_and_frozen_vegetables, pause: false)
                    yuca_root = Category.create(name: "Yuca Root", parent: fresh_and_frozen_vegetables, pause: false)
        fruit_sauces = Category.create(name: "Fruit Sauces", parent: fruits_and_vegetables, pause: false)
    grains_rice_and_cereal = Category.create(name: "Grains, Rice & Cereal", parent: food_products, pause: false)
        amaranth = Category.create(name: "Amaranth", parent: grains_rice_and_cereal, pause: false)
        barley = Category.create(name: "Barley", parent: grains_rice_and_cereal, pause: false)
        buckwheat = Category.create(name: "Buckwheat", parent: grains_rice_and_cereal, pause: false)
        cereal_and_granola = Category.create(name: "Cereal & Granola", parent: grains_rice_and_cereal, pause: false)
        couscous = Category.create(name: "Couscous", parent: grains_rice_and_cereal, pause: false)
        millet = Category.create(name: "Millet", parent: grains_rice_and_cereal, pause: false)
        oats_grits_and_hot_cereal = Category.create(name: "Oats, Grits & Hot Cereal", parent: grains_rice_and_cereal, pause: false)
        quinoa = Category.create(name: "Quinoa", parent: grains_rice_and_cereal, pause: false)
        rice = Category.create(name: "Rice", parent: grains_rice_and_cereal, pause: false)
        rye = Category.create(name: "Rye", parent: grains_rice_and_cereal, pause: false)
        wheat = Category.create(name: "Wheat", parent: grains_rice_and_cereal, pause: false)
    meat_seafood_and_eggs = Category.create(name: "Meat, Seafood & Eggs", parent: food_products, pause: false)
        eggs = Category.create(name: "Eggs", parent: meat_seafood_and_eggs, pause: false)
            egg_whites = Category.create(name: "Egg Whites", parent: eggs, pause: false)
            liquid_and_frozen_eggs = Category.create(name: "Liquid & Frozen Eggs", parent: eggs, pause: false)
            prepared_eggs = Category.create(name: "Prepared Eggs", parent: eggs, pause: false)
            whole_eggs = Category.create(name: "Whole Eggs", parent: eggs, pause: false)
        meat = Category.create(name: "Meat", parent: meat_seafood_and_eggs, pause: false)
            canned_meats = Category.create(name: "Canned Meats", parent: meat, pause: false)
            fresh_and_frozen_meats = Category.create(name: "Fresh & Frozen Meats", parent: meat, pause: false)
            lunch_and_deli_meats = Category.create(name: "Lunch & Deli Meats", parent: meat, pause: false)
        seafood = Category.create(name: "Seafood", parent: meat_seafood_and_eggs, pause: false)
            canned_seafood = Category.create(name: "Canned Seafood", parent: seafood, pause: false)
            fresh_and_frozen_seafood = Category.create(name: "Fresh & Frozen Seafood", parent: seafood, pause: false)
    nuts_and_seeds = Category.create(name: "Nuts & Seeds", parent: food_products, pause: false)
    pasta_and_noodles = Category.create(name: "Pasta & Noodles", parent: food_products, pause: false)
    prepared_foods = Category.create(name: "Prepared Foods", parent: food_products, pause: false)
        prepared_appetizers_and_side_dishes = Category.create(name: "Prepared Appetizers & Side Dishes", parent: prepared_foods, pause: false)
        prepared_meals_and_entrÃ©es = Category.create(name: "Prepared Meals & EntrÃ©es", parent: prepared_foods, pause: false)
    seasonings_and_spices = Category.create(name: "Seasonings & Spices", parent: food_products, pause: false)
        herbs_and_spices = Category.create(name: "Herbs & Spices", parent: seasonings_and_spices, pause: false)
        msg = Category.create(name: "MSG", parent: seasonings_and_spices, pause: false)
        pepper = Category.create(name: "Pepper", parent: seasonings_and_spices, pause: false)
        salt = Category.create(name: "Salt", parent: seasonings_and_spices, pause: false)
    snack_foods = Category.create(name: "Snack Foods", parent: food_products, pause: false)
        breadsticks = Category.create(name: "Breadsticks", parent: snack_foods, pause: false)
        cereal_and_granola_bars = Category.create(name: "Cereal & Granola Bars", parent: snack_foods, pause: false)
            cereal_bars = Category.create(name: "Cereal Bars", parent: cereal_and_granola_bars, pause: false)
            granola_bars = Category.create(name: "Granola Bars", parent: cereal_and_granola_bars, pause: false)
        cheese_puffs = Category.create(name: "Cheese Puffs", parent: snack_foods, pause: false)
        chips = Category.create(name: "Chips", parent: snack_foods, pause: false)
        crackers = Category.create(name: "Crackers", parent: snack_foods, pause: false)
        croutons = Category.create(name: "Croutons", parent: snack_foods, pause: false)
        fruit_snacks = Category.create(name: "Fruit Snacks", parent: snack_foods, pause: false)
        jerky = Category.create(name: "Jerky", parent: snack_foods, pause: false)
        popcorn = Category.create(name: "Popcorn", parent: snack_foods, pause: false)
        pork_rinds = Category.create(name: "Pork Rinds", parent: snack_foods, pause: false)
        pretzels = Category.create(name: "Pretzels", parent: snack_foods, pause: false)
        pudding_and_gelatin_snacks = Category.create(name: "Pudding & Gelatin Snacks", parent: snack_foods, pause: false)
        puffed_rice_cakes = Category.create(name: "Puffed Rice Cakes", parent: snack_foods, pause: false)
        salad_toppings = Category.create(name: "Salad Toppings", parent: snack_foods, pause: false)
        sesame_sticks = Category.create(name: "Sesame Sticks", parent: snack_foods, pause: false)
        snack_cakes = Category.create(name: "Snack Cakes", parent: snack_foods, pause: false)
        sticky_rice_cakes = Category.create(name: "Sticky Rice Cakes", parent: snack_foods, pause: false)
        trail_and_snack_mixes = Category.create(name: "Trail & Snack Mixes", parent: snack_foods, pause: false)
    soups_and_broths = Category.create(name: "Soups & Broths", parent: food_products, pause: false)
    tofu_soy_and_vegetarian_products = Category.create(name: "Tofu, Soy & Vegetarian Products", parent: food_products, pause: false)
        cheese_alternatives = Category.create(name: "Cheese Alternatives", parent: tofu_soy_and_vegetarian_products, pause: false)
        meat_alternatives = Category.create(name: "Meat Alternatives", parent: tofu_soy_and_vegetarian_products, pause: false)
        seitan = Category.create(name: "Seitan", parent: tofu_soy_and_vegetarian_products, pause: false)
        tempeh = Category.create(name: "Tempeh", parent: tofu_soy_and_vegetarian_products, pause: false)
        tofu = Category.create(name: "Tofu", parent: tofu_soy_and_vegetarian_products, pause: false)
        

# Food, Beverages & Tobacco > Tobacco Products
# Food, Beverages & Tobacco > Tobacco Products > Chewing Tobacco
# Food, Beverages & Tobacco > Tobacco Products > Cigarettes
# Food, Beverages & Tobacco > Tobacco Products > Cigars
# Food, Beverages & Tobacco > Tobacco Products > Loose Tobacco
# Food, Beverages & Tobacco > Tobacco Products > Smoking Pipes
# Food, Beverages & Tobacco > Tobacco Products > Vaporizers & Electronic Cigarettes
# Food, Beverages & Tobacco > Tobacco Products > Vaporizers & Electronic Cigarettes > Electronic Cigarettes
# Food, Beverages & Tobacco > Tobacco Products > Vaporizers & Electronic Cigarettes > Vaporizers


# (1..353).each do |category|
#     10.times do
#         Product.create(
#             name: Faker::Food.vegetables,
#             category_id: category,
#             barcode: Faker::Number.number(digits: 6),
#             status: rand(0...1)
#         )
#     end
# end